apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: talys-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/LeonelFeukouo/Gestion_java_argocd.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: talys-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
