apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: talys-app
  name: talys-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: talys-app
  template:
    metadata:
      labels:
        app: talys-app
    spec:
      containers:
      - image: leonelfeukouo/talys_app:v_2
        name: talys-app-container
        ports:
        - containerPort: 8080
